language: python
python: 
  - "2.7"
sudo: required
env: CONTAINER_COUNT=1
matrix:
  include:
      - os: linux
        services:
          - docker
        before_install:
          - make start
        script:
          - make test
          - sudo /home/travis/virtualenv/python2.7/bin/python memcrashed.py -s 172.17.0.2 -t 172.17.0.1 -f
      - os: osx
        language: generic
        before_install:
          - sudo bash /home/travis/alexconrey/pymemcrashed/.travis/install.sh
        script:
          - make test
cache: pip
install:
  - pip install -r requirements.txt
